
# Categories
appetizer = Category.find_or_create_by({name: "appetizer"})
sandwich = Category.find_or_create_by({name: "sandwich"})
pasta = Category.find_or_create_by({name: "pasta"})
dinner = Category.find_or_create_by({name: "dinner"})
pizza = Category.find_or_create_by({name: "pizza"})
kids = Category.find_or_create_by({name: 'kids'})
beverage = Category.find_or_create_by({name: "beverage"})
dessert = Category.find_or_create_by({name: "dessert"})
non_italian = Category.find_or_create_by({name: "non-italian"})


# Appetizer Items
calamari = Item.find_or_create_by({name: "Fried Calamari", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
meatball = Item.find_or_create_by({name: "Meat Ball", description: "Homemade, hand-rolled", price: 2, category_id: 1})
sausage = Item.find_or_create_by({name: "Link Sausage", description: "Italian Link Sauage in Meat Sauce", price: 2, category_id: 1})
garlic_bread_with_cheese = Item.find_or_create_by({name: "Garlic Bread w/Cheese", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
tom_bread = Item.find_or_create_by({name: "Tomatoe Bread", description: "Our homemade bread with fresh garlic, tomatoe, cheese, oregano", price: 10, category_id: 1})
julian_salad = Item.find_or_create_by({name: "Italian Julian Salad", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
house_salad = Item.find_or_create_by({name: "House Salad", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
mushrooms = Item.find_or_create_by({name: "Fried Mushrooms", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
zucchhini = Item.find_or_create_by({name: "Fried Zucchhini", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
half_soup = Item.find_or_create_by({name: "Half Ministrone Soup", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})
full_soup = Item.find_or_create_by({name: "Full Ministrone Soup", description: "Breaded Calamari, Fried, served with cocktail sauce", price: 10, category_id: 1})

# Sandwich Items
meatball = Item.find_or_create_by({name: "Meatball", description: "Description", price: 10, category_id: 2})
sausage = Item.find_or_create_by({name: "Sausage", description: "Description", price: 10, category_id: 2})
beef = Item.find_or_create_by({name: "Beef", description: "Description", price: 10, category_id: 2})
capozios = Item.find_or_create_by({name: "Capozio's Sub", description: "Description", price: 10, category_id: 2})
half_capozios = Item.find_or_create_by({name: "Half Capozio's Sub", description: "Description", price: 10, category_id: 2})
ham = Item.find_or_create_by({name: "Ham", description: "Description", price: 10, category_id: 2})

# Pasta Items
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})
# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})

# Dinner Items
chicken_alfreado = Item.find_or_create_by({name: "Chicken Alfreado", description: "Description", price: 10, category_id: 4})
manicotti = Item.find_or_create_by({name: "Manicotti", description: "Description", price: 10, category_id: 4})
lasagna = Item.find_or_create_by({name: "Lasagna", description: "Description", price: 10, category_id: 4})
pollo_parm = Item.find_or_create_by({name: "Pollo Parmesan", description: "Description", price: 10, category_id: 4})
veal_parm = Item.find_or_create_by({name: "Veal Parmesan", description: "Description", price: 10, category_id: 4})
tort_pros_alf = Item.find_or_create_by({name: "Tortellini Prosciutto Alfredo", description: "Description", price: 10, category_id: 4})
shrimp_and_peppers = Item.find_or_create_by({name: "Shrimp & Peppers", description: "Description", price: 10, category_id: 4})
shrimp_alfredo = Item.find_or_create_by({name: "Shrimp Alfredo", description: "Description", price: 10, category_id: 4})
canneloni = Item.find_or_create_by({name: "Cannelloni", description: "Description", price: 10, category_id: 4})
spin_las = Item.find_or_create_by({name: "Spinach Lasagna", description: "Description", price: 10, category_id: 4})
egg_plant_parm = Item.find_or_create_by({name: "Egg Plant Parmesan", description: "Description", price: 10, category_id: 4})
seafood_pasta = Item.find_or_create_by({name: "Seafood Pasta", description: "Description", price: 10, category_id: 4})
veal_and_peppers = Item.find_or_create_by({name: "Veal & Peppers", description: "Description", price: 10, category_id: 4})
calamari_in_red_sauce = Item.find_or_create_by({name: "Calamari in Red Sauce", description: "Description", price: 10, category_id: 4})


# item = Item.find_or_create_by({name: "item", description: "Description", price: 10, category_id: 2})

# Pizza Ingredients
sausage = Ingredient.find_or_create_by({category_id: 5, name: "Sausage"})
pepperoni = Ingredient.find_or_create_by({category_id: 5, name: "Pepperoni"})
meatball = Ingredient.find_or_create_by({category_id: 5, name: "Meatball"})
ham = Ingredient.find_or_create_by({category_id: 5, name: "Ham"})
beef = Ingredient.find_or_create_by({category_id: 5, name: "Beef"})
bacon = Ingredient.find_or_create_by({category_id: 5, name: "Bacon"})
green_pepper = Ingredient.find_or_create_by({category_id: 5, name: "Green Pepper"})
onion = Ingredient.find_or_create_by({category_id: 5, name: "Onion"})
black_olive = Ingredient.find_or_create_by({category_id: 5, name: "Black Olive"})
green_olive = Ingredient.find_or_create_by({category_id: 5, name: "Green Olive"})
mushroom = Ingredient.find_or_create_by({category_id: 5, name: "Mushroom"})
anchovie = Ingredient.find_or_create_by({category_id: 5, name: "Anchovie"})
pineapple = Ingredient.find_or_create_by({category_id: 5, name: "Pineapple"})
spinach = Ingredient.find_or_create_by({category_id: 5, name: "Spinach"})
broccoli = Ingredient.find_or_create_by({category_id: 5, name: "Broccoli"})
articoke_heart = Ingredient.find_or_create_by({category_id: 5, name: "Articoke Heart"})
tomatoe = Ingredient.find_or_create_by({category_id: 5, name: "Tomato"})

# Orders
# order1 = Order.create({first_name: "Ignacio", last_name: "Espino", total: 10, order_items_attributes: [{item_id: 1, quantity: 2}, {item_id: 2, quantity: 5}]})
# order2 = Order.create({first_name: "Michele", last_name: "Kim", total: 20, order_items_attributes: [{item_id: 2, quantity: 2}, {item_id: 2, quantity: 5}]})
# order3 = Order.create({first_name: "Absolem", last_name: "Cherinet", total: 30, order_items_attributes: [{item_id: 1, quantity: 2}, {item_id: 2, quantity: 5}]})
# order4 = Order.create({first_name: "John", last_name: "Smith", total: 40, order_items_attributes: [{item_id: 4, quantity: 2}, {item_id: 4, quantity: 5}]})
# order5 = Order.create({first_name: "Teresa", last_name: "Espino", total: 50, order_items_attributes: [{item_id: 3, quantity: 2}, {item_id: 2, quantity: 5}]})
# order6 = Order.create({first_name: "Erica", last_name: "Espino", total: 60, order_items_attributes: [{item_id: 5, quantity: 2}, {item_id: 7, quantity: 5}]})
# order7 = Order.create({first_name: "Judy", last_name: "Espino", total: 70, order_items_attributes: [{item_id: 1, quantity: 2}, {item_id: 2, quantity: 5}]})